- type: dropdown
  name: Select Application
  items: []
  source:
    cmd: |
      civo kubernetes applications ls --output json
    path-id: $[*].name
    path-name: $[*].name
    cache: civo_kubernetes_applications_list
  produces:
    - variable: application_name
