- item-types: docker-xxx
  fields:
    state:
      path: "$.state"
    size:
      path: "$.plan"
    location:
      path: "$.zone"
    size_cores:
      path: "$.core_number"
    size_memory:
      path: "$.memory_amount"
    size_disk:
      path: "$[0].specs.disk"
    image:
      path: "$[0].image"
